version: '3.8'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8080:8080"   # Jenkins Web
      - "50000:50000" # Agentes
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  api-financeiro:
    image: api-financeiro:latest
    container_name: api-financeiro
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - jenkins

volumes:
  jenkins_home:
